const WORDS = {
  like: { ja: 'すき', icon: '♡', type: 'action' },
  drink: { ja: 'のむ', icon: '🥤', type: 'action' },
  eat: { ja: 'たべる', icon: '🍽️', type: 'action' },
  cook: { ja: 'つくる', icon: '🍳', type: 'action' },
  play: { ja: 'する・あそぶ', icon: '⚽', type: 'action' },
  watch: { ja: 'みる', icon: '👀', type: 'action' },
  teach: { ja: 'おしえる', icon: '👩‍🏫', type: 'action' },
  study: { ja: 'べんきょうする', icon: '📚', type: 'action' },
  want: { ja: 'ほしい', icon: '✨', type: 'action' },
  drive: { ja: 'うんてんする', icon: '🚗', type: 'action' },
  have: { ja: 'もっている', icon: '🎒', type: 'action' },
  read: { ja: 'よむ', icon: '📖', type: 'action' },
  sing: { ja: 'うたう', icon: '🎵', type: 'action' },
  live: { ja: 'すんでいる', icon: '🏠', type: 'action' },
  swim: { ja: 'およぐ', icon: '🏊', type: 'action' },
  run: { ja: 'はしる', icon: '🏃', type: 'action' },
  milk: { ja: 'ぎゅうにゅう', icon: '🥛', type: 'thing' },
  juice: { ja: 'ジュース', icon: '🧃', type: 'thing' },
  coffee: { ja: 'コーヒー', icon: '☕', type: 'thing' },
  tea: { ja: 'おちゃ', icon: '🍵', type: 'thing' },
  curry: { ja: 'カレー', icon: '🍛', type: 'thing' },
  pizza: { ja: 'ピザ', icon: '🍕', type: 'thing' },
  steak: { ja: 'ステーキ', icon: '🥩', type: 'thing' },
  pasta: { ja: 'パスタ', icon: '🍝', type: 'thing' },
  soccer: { ja: 'サッカー', icon: '⚽', type: 'thing' },
  tennis: { ja: 'テニス', icon: '🎾', type: 'thing' },
  baseball: { ja: 'やきゅう', icon: '⚾', type: 'thing' },
  'ping-pong': { ja: 'ピンポン', icon: '🏓', type: 'thing' },
  English: { ja: 'えいご', icon: '🔤', type: 'thing' },
  math: { ja: 'さんすう', icon: '➕', type: 'thing' },
  science: { ja: 'りか', icon: '🔬', type: 'thing' },
  Japanese: { ja: 'こくご', icon: '🗾', type: 'thing' },
  car: { ja: 'くるま', icon: '🚗', type: 'thing' },
  truck: { ja: 'トラック', icon: '🚚', type: 'thing' },
  bus: { ja: 'バス', icon: '🚌', type: 'thing' },
  train: { ja: 'でんしゃ', icon: '🚆', type: 'thing' },
  apples: { ja: 'りんご', icon: '🍎', type: 'thing' },
  bananas: { ja: 'バナナ', icon: '🍌', type: 'thing' },
  carrots: { ja: 'にんじん', icon: '🥕', type: 'thing' },
  nuts: { ja: 'ナッツ', icon: '🥜', type: 'thing' },
  big: { ja: 'おおきい', icon: '⬆️', type: 'word' },
  small: { ja: 'ちいさい', icon: '⬇️', type: 'word' },
  new: { ja: 'あたらしい', icon: '🌟', type: 'word' },
  cute: { ja: 'かわいい', icon: '🎀', type: 'word' },
  pants: { ja: 'ズボン', icon: '👖', type: 'thing' },
  shoes: { ja: 'くつ', icon: '👟', type: 'thing' },
  gloves: { ja: 'てぶくろ', icon: '🧤', type: 'thing' },
  socks: { ja: 'くつした', icon: '🧦', type: 'thing' },
  taxi: { ja: 'タクシー', icon: '🚕', type: 'thing' },
  rugby: { ja: 'ラグビー', icon: '🏉', type: 'thing' },
  golf: { ja: 'ゴルフ', icon: '⛳', type: 'thing' },
  ten: { ja: '10', icon: '🔟', type: 'word' },
  flowers: { ja: 'はな', icon: '🌼', type: 'thing' },
  ring: { ja: 'ゆびわ', icon: '💍', type: 'thing' },
  watchNoun: { ja: 'うでどけい', icon: '⌚', type: 'thing', say: 'watch' },
  shirt: { ja: 'シャツ', icon: '👕', type: 'thing' },
  jacket: { ja: 'ジャケット', icon: '🧥', type: 'thing' },
  pink: { ja: 'ピンク', icon: '🩷', type: 'word' },
  blue: { ja: 'あお', icon: '🔵', type: 'word' },
  green: { ja: 'みどり', icon: '🟢', type: 'word' },
  white: { ja: 'しろ', icon: '⚪', type: 'word' },
  pandas: { ja: 'パンダ', icon: '🐼', type: 'thing' },
  koalas: { ja: 'コアラ', icon: '🐨', type: 'thing' },
  monkeys: { ja: 'さる', icon: '🐵', type: 'thing' },
  penguins: { ja: 'ペンギン', icon: '🐧', type: 'thing' },
  yard: { ja: 'にわ', icon: '🌳', type: 'place' },
  park: { ja: 'こうえん', icon: '🛝', type: 'place' },
  kitchen: { ja: 'キッチン', icon: '🍳', type: 'place' },
  pool: { ja: 'プール', icon: '🏊', type: 'place' },
  woods: { ja: 'もり', icon: '🌲', type: 'place' },
  London: { ja: 'ロンドン', icon: '🇬🇧', type: 'place' },
  Moscow: { ja: 'モスクワ', icon: '🇷🇺', type: 'place' },
  Bangkok: { ja: 'バンコク', icon: '🇹🇭', type: 'place' },
  Tokyo: { ja: 'とうきょう', icon: '🗼', type: 'place' },
  lunch: { ja: 'ひるごはん', icon: '🍱', type: 'time' },
  dinner: { ja: 'ばんごはん', icon: '🍽️', type: 'time' },
  school: { ja: 'がっこう', icon: '🏫', type: 'time' },
  Kumon: { ja: 'くもん', icon: '✏️', type: 'time' },
  work: { ja: 'しごと', icon: '💼', type: 'time' },
  before: { ja: 'まえ', icon: '⏪', type: 'word' },
  after: { ja: 'あと', icon: '⏩', type: 'word' },
  six: { ja: '6じ', icon: '🕕', type: 'time' },
  seven: { ja: '7じ', icon: '🕖', type: 'time' },
  eight: { ja: '8じ', icon: '🕗', type: 'time' },
  nine: { ja: '9じ', icon: '🕘', type: 'time' },
  here: { ja: 'ここ', icon: '📍', type: 'place' },
  hungry: { ja: 'おなかがすいた', icon: '😋', type: 'word' },
  cheese: { ja: 'チーズ', icon: '🧀', type: 'thing' },
  'apple juice': { ja: 'りんごジュース', icon: '🧃', type: 'thing' },
};

const STAGES = [
  { id: 'drinks', title: 'のみもの', badge: '🥛', words: ['like', 'drink', 'milk', 'juice', 'coffee', 'tea'], lines: ['I like milk.', 'I like juice.', 'I like coffee.', 'I like tea.', 'I drink milk.', 'I drink juice.', 'I drink coffee.', 'I drink tea.'] },
  { id: 'food', title: 'ごはん', badge: '🍛', words: ['eat', 'cook', 'curry', 'pizza', 'steak', 'pasta'], lines: ['I eat curry.', 'I eat pizza.', 'I eat steak.', 'I eat pasta.', 'I cook curry.', 'I cook pizza.', 'I cook steak.', 'I cook pasta.'] },
  { id: 'sports', title: 'スポーツ', badge: '⚽', words: ['play', 'watch', 'soccer', 'tennis', 'baseball', 'ping-pong'], lines: ['I play soccer.', 'I play tennis.', 'I play baseball.', 'I play ping-pong.', 'I watch soccer.', 'I watch tennis.', 'I watch baseball.', 'I watch ping-pong.'] },
  { id: 'subjects', title: 'おべんきょう', badge: '📚', words: ['teach', 'study', 'English', 'math', 'science', 'Japanese'], lines: ['I teach English.', 'I teach math.', 'I teach science.', 'I teach Japanese.', 'I study English.', 'I study math.', 'I study science.', 'I study Japanese.'] },
  { id: 'vehicles', title: 'のりもの', badge: '🚗', words: ['want', 'drive', 'car', 'truck', 'bus', 'train'], lines: ['I want a car.', 'I want a truck.', 'I want a bus.', 'I want a train.', 'I drive a car.', 'I drive a truck.', 'I drive a bus.', 'I drive a train.'] },
  { id: 'sizes', title: 'おおきい・ちいさい', badge: '🍎', words: ['eat', 'big', 'small', 'apples', 'bananas', 'carrots', 'nuts'], lines: ['I eat big apples.', 'I eat big bananas.', 'I eat big carrots.', 'I eat big nuts.', 'I eat small apples.', 'I eat small bananas.', 'I eat small carrots.', 'I eat small nuts.'] },
  { id: 'clothes', title: 'あたらしい・かわいい', badge: '👟', words: ['have', 'new', 'cute', 'pants', 'shoes', 'gloves', 'socks'], lines: ['I have new pants.', 'I have new shoes.', 'I have new gloves.', 'I have new socks.', 'I have cute pants.', 'I have cute shoes.', 'I have cute gloves.', 'I have cute socks.'] },
  { id: 'driveQuestion', title: 'バスをうんてんする？', badge: '🚌', words: ['drive', 'bus', 'taxi'], lines: ['Do you drive a bus?', 'Yes, I do.', "No, I don't.", 'Do you drive a taxi?', 'Yes, I do.', "No, I don't."] },
  { id: 'playQuestion', title: 'スポーツする？', badge: '🎾', words: ['play', 'soccer', 'tennis', 'rugby', 'golf'], lines: ['Do you play soccer?', 'Yes, I do.', "No, I don't.", 'I play rugby.', 'Do you play tennis?', 'Yes, I do.', "No, I don't.", 'I play golf.'] },
  { id: 'nutsStory', title: 'ナッツのおはなし', badge: '🥕', words: ['have', 'ten', 'nuts', 'eat', 'like', 'big', 'small', 'carrots', 'flowers'], lines: ['I have ten nuts.', 'Do you eat nuts?', "No, I don't.", 'I like big carrots.', 'Do you eat nuts?', "No, I don't.", 'I like small flowers.', 'Do you eat nuts?', 'Yes, I do.', 'Yummy!'] },
  { id: 'whichThing', title: 'どっちがほしい？', badge: '💍', words: ['want', 'ring', 'watchNoun', 'shirt', 'jacket'], lines: ['Which do you want?', 'I want the ring.', 'I want the watch.', 'Which do you want?', 'I want the shirt.', 'I want the jacket.'] },
  { id: 'colors', title: 'いろ', badge: '🎨', words: ['want', 'pink', 'blue', 'green', 'white'], lines: ['What color do you want?', 'I want pink.', 'I want blue.', 'What color do you want?', 'I want green.', 'I want white.'] },
  { id: 'animals', title: 'どうぶつ', badge: '🐼', words: ['like', 'pandas', 'koalas', 'monkeys', 'penguins'], lines: ['What animal do you like?', 'I like pandas.', 'I like koalas.', 'What animal do you like?', 'I like monkeys.', 'I like penguins.'] },
  { id: 'placesAction', title: 'どこで？', badge: '🌳', words: ['read', 'sing', 'yard', 'park', 'car', 'kitchen'], lines: ['I read in the yard.', 'I read in the park.', 'I read in the car.', 'I read in the kitchen.', 'I sing in the yard.', 'I sing in the park.', 'I sing in the car.', 'I sing in the kitchen.'] },
  { id: 'wherePlay', title: 'どこであそぶ？', badge: '🛝', words: ['play', 'yard', 'park', 'pool', 'woods'], lines: ['Where do you play?', 'I play in the yard.', 'I play in the park.', 'Where do you play?', 'I play in the pool.', 'I play in the woods.'] },
  { id: 'whereLive', title: 'どこにすんでる？', badge: '🗼', words: ['live', 'London', 'Moscow', 'Bangkok', 'Tokyo'], lines: ['Where do you live?', 'I live in London.', 'I live in Moscow.', 'Where do you live?', 'I live in Bangkok.', 'I live in Tokyo.'] },
  { id: 'after', title: '〜のあと', badge: '⏩', words: ['swim', 'run', 'after', 'lunch', 'dinner', 'school', 'Kumon'], lines: ['I swim after lunch.', 'I swim after dinner.', 'I swim after school.', 'I swim after Kumon.', 'I run after lunch.', 'I run after dinner.', 'I run after school.', 'I run after Kumon.'] },
  { id: 'before', title: '〜のまえ', badge: '⏪', words: ['study', 'before', 'lunch', 'dinner', 'school', 'work'], lines: ['When do you study?', 'I study before lunch.', 'I study before dinner.', 'When do you study?', 'I study before school.', 'I study before work.'] },
  { id: 'timeDinner', title: 'なんじにたべる？', badge: '🕕', words: ['eat', 'dinner', 'six', 'seven', 'eight', 'nine'], lines: ['When do you eat dinner?', 'I eat at six.', 'I eat at seven.', 'When do you eat dinner?', 'I eat at eight.', 'I eat at nine.'] },
  { id: 'finalStory', title: 'さいごのおはなし', badge: '🏠', words: ['live', 'here', 'hungry', 'eat', 'dinner', 'want', 'cheese', 'apple juice', 'run'], lines: ['Do you live here?', 'Yes. Come in!', 'Are you hungry?', 'Yes, I am.', "Let's eat dinner!", 'Which do you want?', 'I want the cheese.', 'What juice do you want?', 'I want apple juice.', 'Run!'] },
];
